### ISSUE TITLE
Movement / Visual memory

### ISSUE THREAD

**Issue by Sentdex** [Sentdex/pygta5#10]
At the moment, I think memory will prove to be the most useful enhancement to what we have so far. 

Thus far, I've considered an encoder/decoder-like setup, with first the convnet, then the recurrent net which will take the final prediction, the previous 100 frames of moves, and then put out the output. 

I am not certain this is totally necessary, I am also tinkering with just simply taking a mean of predicted movements in the last 5-10 frames, with some caveats.

**Comment by Ghost---Shadow** [comment]
Another thing I have tried [(on a different project)](https://github.com/Ghost---Shadow/BoilingMilkDetector) is having the last say 3-5 frames as separate channels in the convnet. The frames would move in and out in a FIFO basis. 

This gives the much needed temporal data to the convnet and removes the need for RNNs which take literally forever to train.

**Comment by zxzhijia** [comment]
I would suggest to use steering angle to control the car other than only w,s,d,a. What do you think?

**Comment by Flandan** [comment]
I agree @zxzhijia as right now its pretty tricky to get a dataset together as we need to throw away >60% just to normalise. I also think that it is causing the issues of uncertainty in actions. Its possible that short term memory could solve this though.

Right now, even in a hard turn, the dataset will contain both hard left/right and straight ahead classifications with almost identical images. An idea I had for this was to take the last 20 or so frames and calculate the fraction of time dedicated to each keypress, using these fractions as the input weights. I could see this working for a car going at a relatively constant speed. I think for starting/stopping/braking some form of memory would be essential.
