### ISSUE TITLE
Better intuition for the  Waypoint Mechanism?

### ISSUE THREAD

**Issue by CT83** [Sentdex/pygta5#100]
Could someone please point me to relevant resources on the working of the *Waypoint Mechanism*?
I failed to find any explanation on GitHub or in the Playlist on how it works.

Is it done by training the CNN on huge amount of game frames with mini-map (and road) and the key inputs, till it learns the correlation between both of these? Or is there an alternative?

**Comment by PeterGardas** [comment]
Yes i thing it is that way. But be creative. Maybe you will find something better! :D

Peter Gardas
