### ISSUE TITLE
please help me i dont know what to do! please!

### ISSUE THREAD

**Issue by ThorHenrik** [Sentdex/pygta5#102]
hi, i need to start with im really new to python (i had not done python before this series u made) but i understand what im doing and  the basics. but i get so much problem with tensorflow now and i have tried for long and i cant se fix anywhere on internet. error: 
WARNING:tensorflow:From C:\Users\ththo\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From C:\Users\ththo\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\objectives.py:66: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "C:\Users\ththo\Desktop\Gta 5 AI Test\train_model.py", line 25, in <module>
    model.fit({'input': X}, {'targets': Y}, n_epochs=EPOCHS,
NameError: name 'X' is not defined
>>> 
i cant fix it an i really need to fix it to continue. thank you for any help!!

**Comment by SnailingGoat** [comment]
Well it is saying that `X` was not defined?...

Send your code for train_model.py
