### ISSUE TITLE
balance_data.py is not creating the balanced data file

### ISSUE THREAD

**Issue by TrackLab** [Sentdex/pygta5#110]
After I created some training data I got the file "training_data.npy"
But the balance_data.py code is not giving out any file, so I cannot start the Training. This is what the programm returns when running balance_data.py

[https://i.gyazo.com/6cd66d87e83b2629fdebc5972c6ff88b.png](url)

**Comment by PeterGardas** [comment]
It returns the right thing, could you share your code? That would help determining what the issue is!

Thank you

Peter Gardas

**Comment by PeterGardas** [comment]
Are you sure you have not modified it? Have you looked closely to your file? Or have you modified the path that the balanced data is saved?

Peter

**Comment by Tr4ckster** [comment]
> 
> 
> Are you sure you have not modified it? Have you looked closely to your file? Or have you modified the path that the balanced data is saved?
> 
> Peter

No. I downloaded the ZIP and put it on my Desktop. Besides running the scripts i didnt do anything. And like i said, collecting training data works fine.

**Comment by PeterGardas** [comment]
Please, show me your balance_training_data.py so i can inspect it.

**Comment by Tr4ckster** [comment]
`# balance_data.py

import numpy as np
import pandas as pd
from collections import Counter
from random import shuffle

train_data = np.load('training_data.npy')

df = pd.DataFrame(train_data)
print(df.head())
print(Counter(df[1].apply(str)))

lefts = []
rights = []
forwards = []

shuffle(train_data)

for data in train_data:
    img = data[0]
    choice = data[1]

    if choice == [1,0,0]:
        lefts.append([img,choice])
    elif choice == [0,1,0]:
        forwards.append([img,choice])
    elif choice == [0,0,1]:
        rights.append([img,choice])
    else:
        print('no matches')


forwards = forwards[:len(lefts)][:len(rights)]
lefts = lefts[:len(forwards)]
rights = rights[:len(forwards)]

final_data = forwards + lefts + rights
shuffle(final_data)

np.save('training_data.npy', final_data)




`

**Comment by Phillyclause89** [comment]
In the last line of the code you pasted, `np.save('training_data.npy', final_data)` is saving to the same file name as your loaded data file, basically overwriting it. Changing it to something like `np.save('balanced_training_data.npy', final_data)` should have it save to a new file instead of overwriting the existing one.
