### ISSUE TITLE
Vehicle only choosing "Straight" direction

### ISSUE THREAD

**Issue by tycrek** [Sentdex/pygta5#112]
I have around 60,000 frames from data collecting, those were trained to a model after 5 epochs using the v0.0.3 code.

For some reason in game, it only chooses the straight direction and NEVER turns or reverses unless its evasive maneuvers. The only change I made was in `3. test_model.py`:

            #prediction = np.array(prediction) * np.array([4.5, 0.1, 0.1, 0.1, 1.8, 1.8, 0.5, 0.5, 0.2])
            prediction = np.array(prediction) * np.array([0.7, 0.1, 0.1, 0.1, 2.0, 2.0, 0.5, 0.5, 0.4])

That was a drastic attempt to try and make it go somewhere else, but still straight.

Do I need more epochs or is something wrong with the 0.0.3 code? If anyone has a working fork of this I would love to see that as well.

**Comment by kir486680** [comment]
> Have you called the model.save() function in your training code? I had similar issue becouse my model was not saving, so it was really bad/going only left.
> 
> Peter

After model.fit?

**Comment by PeterGardas** [comment]
> > Have you called the model.save() function in your training code? I had similar issue becouse my model was not saving, so it was really bad/going only left.
> > Peter
> 
> After model.fit?

Yes

**Comment by Mombuca22** [comment]
I have the same issue and model has been saved.

**Comment by PeterGardas** [comment]
> I have the same issue and model has been saved.

Could you please share your code so we could elaborate.

Peter

**Comment by tycrek** [comment]
Woooops. I only just realized this has been sitting open for two years... I don't even have that code anymore.

@PeterGardas, I'm fine with closing this if you want to close it

**Comment by PeterGardas** [comment]
@tycrek If you want you can close it.
