### ISSUE TITLE
Python only presses and doesn't hold

### ISSUE THREAD

**Issue by kittrz9** [Sentdex/pygta5#121]
I'm trying to make something like the Twitch plays Pokemon livestream from a few years ago, where people send inputs from a chat client and have them be performed in game (something like "!input left 5" would hold left for 5 seconds).
I'm using some of the code from the 3rd video in the tutorial series (Direct Input - Python plays Grand Theft Auto 5 p.3) to hold down a key. When I try to hold one key down using this code, it only presses the key down once when PressKey(keyMap[sys.argv[1]]) is executed.  The directkeys.py file is exactly the same as in the repository. Here is the code that is meant to hold down the key

```python
# Import things
import sys
import time
from directkeys import PressKey, ReleaseKey

# Key map that converts inputs from the javascript into the scan codes for the keys that need to be pressed for that input
keyMap = {
	"up" : 0xC8,
	"down" : 0xD0,
	"left" : 0xCB,
	"right" : 0xCD,
	"a" : 0x2E,
	"b" : 0x2D,
	"x" : 0x1F,
	"y" : 0x2C,
	"l" : 0x1E,
	"r" : 0x20,
	"start" : 0x10,
	"select" : 0x12
}


# Get the inputs from the bot and hold the key down for the specified amount of
if __name__ == "__main__":
	print(sys.argv[1], " ", sys.argv[2])
	print("down")
	PressKey(keyMap[sys.argv[1]])
	time.sleep(float(sys.argv[2]))
	print("up")
	ReleaseKey(keyMap[sys.argv[1]])
```

I have tried just testing code in directkeys.py
```python
if __name__ == '__main__':
    while (True):
        PressKey(0x11)
        time.sleep(1)
        ReleaseKey(0x11)
        time.sleep(1)
```
This code still produces the same problem, it only sends one w every time it loops, so I don't know what could be causing the issue

**Comment by Corpio3** [comment]
Remove the ReleaseKey and it will be holding your key all time until you stop the loop and press that key again by yourself

**Comment by nixon-nyx** [comment]
You probably need to run them as administrator.
