### ISSUE TITLE
failed to initialize cudnn

### ISSUE THREAD

**Issue by johnny643** [Sentdex/pygta5#125]
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Conv2D/Conv2D (defined at C:\Users\johnny\AppData\Roaming\Python\Python36\site-packages\tflearn\layers\conv.py:99) ]]

**Comment by johnny643** [comment]
cuda 10 and cudnn version is 7.3.1

**Comment by Tyler-Barham** [comment]
This may be caused by your GPU not having enough memory. You could try reducing the batch size or try a smaller model.
