### ISSUE TITLE
Grab Screen in other OS

### ISSUE THREAD

**Issue by S1M0N38** [Sentdex/pygta5#13]
Inspired by your GTA-series, I want to develop an IA able to play other game or able to interact with a android emulator, but I on Mac and I got stuck on the problem to grab the screen with a decent fps. To solve the problem I found a module called [MSS](https://python-mss.readthedocs.io/en/dev/index.html) (written in pure python, working on windows, mac, linux) capable to grab the screen at ~40 fps at 800x400 resolution.
```python
import numpy as np
import cv2
import time
from mss import mss
from PIL import Image

# Macbook have a bug about box's dimensions, can be just multiple of 16
# but this bug will be fix soon in the next release

box = { "top": 45, "left": 0, "width": 480, "height": 320}
sct = mss()

while True:

    t = time.time()
    sct.get_pixels(box)
    image = Image.frombytes('RGB', (sct.width, sct.height), sct.image)

    # Could be useful in MAC OS    
    # b, g, r = image.split()
    # image = Image.merge("RGB", (r, g, b))

    cv2.imshow('test', np.array(image))
    print('fps: {}'.format(1/(time.time()-t)))

    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
        
```

**Comment by Sentdex** [comment]
Thanks for sharing this. It has taken me a while to respond, been super busy. If you want, you can supply a PR and either create a mac-specific grabscreen.py like grabscreen-mac.py, or add an operating system check to the grabscreen.py and do your way. An operating system check would be ideal. I'll leave this open for a bit. If you just want me to do it, I'll go for it, but you can have the credit for the find with a PR.

**Comment by cschar** [comment]
Nice Job Simon!
I'm following along this series w/ a 2011 macbook pro, the color switch was a hiccup for me too. This addition would be welcome for newcomers with Macs.

**Comment by BoboTiG** [comment]
Hello,

I am working on a new version of MSS to have a more pythonic code base and to ease/power that kind of stuff:
- by implementing the Numpy array interface;
- and to let the user change the way pixels are stored (by default, you will have access to raw data in BGRA, RGB and perhaps grayscale RGB [I am hesitating as you could to that efficiently with OpenCV]).

I ran benchmarks on the 3 platforms and it is more or less way faster everywhere. I'ill keep in touch, curios to see results if you planned to test. And, of course, I added examples code to interact with PIL, Numpy and OpenCV.

**Comment by BoboTiG** [comment]
It is online! The version 3.0.0 has a fresh new API, more pythonic. And it is **really** fast. Just upgrade via `pip` and see [examples](https://python-mss.readthedocs.io/en/dev/examples.html) for details.

**Comment by lamhoangtung** [comment]
@BoboTiG can you share you code to get 80-120fps. thanks you so much for that

**Comment by BoboTiG** [comment]
Of course, a copy from the [OpenCV/Numpy example](https://python-mss.readthedocs.io/en/dev/examples.html#opencv-numpy):

    import time

    import cv2
    import mss
    import numpy


    with mss.mss() as sct:
        box = {'top': 40, 'left': 0, 'width': 800, 'height': 640}

        while 'Screen capturing':
            t = time.time()

            # Get raw pixels from the screen, save it to a Numpy array
            img = numpy.array(sct.grab(box))

            # Display the picture
            cv2.imshow('OpenCV/Numpy normal', img)

            # Display the picture in grayscale
            # cv2.imshow('OpenCV/Numpy grayscale',
            #            cv2.cvtColor(img, cv2.COLOR_BGRA2GRAY))

            print('fps: {0}'.format(1 / (time.time()-t)))
            if cv2.waitKey(25) & 0xFF == ord('q'):
                cv2.destroyAllWindows()
                break

**Comment by lamhoangtung** [comment]
Thanks you @BoboTiG

**Comment by Snorn** [comment]
Thank you @BoboTiG

**Comment by tejaskhot** [comment]
@BoboTiG How can I save the frames at a high fps using the MSS method you mentioned? I am able to stream at a very high fps but saving with `mss.tools.to_png` slows it down to 10 fps.

**Comment by BoboTiG** [comment]
@tejaskhot and others, it you xwant to give some help => BoboTiG/python-mss/issues/45 🥇

**Comment by MonkeyBot2020** [comment]
I tried to create a simple program which captures screenshots (using mss) and gets tensorflow to predict/detect elements in the images, but it's not working. Here's part of the code:

    import cv2
    import mss
    import numpy as np
    from PIL import Image

    #Import TFNet
    from darkflow.net.build import TFNet
    import matplotlib.pyplot as plt

    #Specify the dictonary.
    options = {
        'model':'cfg/yolo.cfg',
        'load':'bin/yolov2.weights',
        'threshold': 0.3
    }
    tfnet = TFNet(options)

    #Creates an endless loop for high-speed image acquisition...
    while (True):
        with mss.mss() as sct:

        #Get raw pixels from the screen
        sct_img = sct.grab(sct.monitors[1])

        #Convert image to a numpy array
        img = np.array(sct_img)
        result = tfnet.return_predict(img)

        print(result)

Could someone tell me where I'm going wrong? It returns the following error every time:
`ValueError: Cannot feed value of shape (1, 608, 608, 4) for Tensor 'input:0', which has shape '(?, 608, 608, 3)'`

Please give code examples. Thanks in advance.

**Comment by BoboTiG** [comment]
First, move MSS instanciaton outside the loop, you will win a lot ;)

I *think* the issue is that you are giving BGRA to Tensor, and it wants RGB. You can try [something like](https://python-mss.readthedocs.io/examples.html#bgra-to-rgb):

    #Convert image to a numpy array
    img = np.array(sct_img, dtype=np.uint8)
    img = np.flip(img[:, :, :3], 2)
    result = tfnet.return_predict(img)

Or perhaps better: tell Tensor that you will give it BGRA (the last shape value).

**Comment by MonkeyBot2020** [comment]
Thanks for that! I followed your advice and have since added more to my program and made the screen grabbing bit a function. Here's just the screen-grabbing code. It works, but is extremely slow (my PC is a toaster). I need your opinion: have I made any mistakes and are there any ways that I make this bit faster?

     import cv2
     import mss
     import numpy as np
     from PIL import Image

     #Initialize monitor variable
     monitor = {'top': 46, 'left': 8, 'width': 1280, 'height': 720}
     sct = mss.mss()

     def grab_screen():
         #Get raw pixels from the screen and create an image
         sct_img = sct.grab(monitor)
         img = Image.frombytes('RGB', sct_img.size, sct_img.bgra, 'raw', 'BGRX')

         #Convert image to a numpy array
         img = np.array(img)

         #print(result)
         return img

I barely get 1 FPS on my toaster...

**Comment by BoboTiG** [comment]
What if you try the snippet I proposed with `numpy.flip()`?
```python
while True:
    # Get raw pixels from the screen and create an image
    sct_img = sct.grab(monitor)

    # Convert image to a numpy array
    img = np.array(sct_img, dtype=np.uint8)
    img = np.flip(img[:, :, :3], 2)
```

**Comment by MonkeyBot2020** [comment]
Sorry for the noob question, but why would numpy.flip() speed things up?

**Comment by BoboTiG** [comment]
Numpy is implemented in C and is known to work well with array data. Just try and let us know.
I benchmarked differents solutions and `numpy.flip` is the winner.

**Comment by MonkeyBot2020** [comment]
Sorry for the long hiatus - but I tried it and yes, it is faster. Thank you!

**Comment by ScriptBono** [comment]
I'm getting the following error on Ubuntu 17.10

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  7
  Current serial number in output stream:  7
```

Did anyone experience the same or has a work around for Ubuntu?
