### ISSUE TITLE
How to check if we are training on GPU or CPU?

### ISSUE THREAD

**Issue by Denrose11** [Sentdex/pygta5#130]
I am trying to train the v .03 with my training data. While training my cpu is about 30% and 58% Ram usage. But GPU usage is 0% but when it starts to train each sample it just goes between 70-100% for just one sec. Is everything fine. If i am training on CPU how should i train on GPU. I have tensorflow gpu installed.

Specs:-I7 7700HQ
16 gb ram
1060 6 gb.
windows 10 home updated

**Comment by therealchiendat** [comment]
Are you using CUDA 10 by any chance? I am not 100% sure but I had multiple issues with CUDA 10. I am suggesting to try CUDA 9.

**Comment by Denrose11** [comment]
> Are you using CUDA 10 by any chance? I am not 100% sure but I had multiple issues with CUDA 10. I am suggesting to try CUDA 9.

Hey! thank you for reply. I m using CUDA 9 only and now its running fine. Any guess how much its gonna take to train on gtx 1060. I am running V .02 and i gave training data of worth 24 hours of driving. I tried V.03 but i guess 6gb VRAM was not sufficient for that, may be because of higher resolution. I can lower the resolution but can't figure out to decrease the batch size. So can anyone tell me how to decrease the batch size? And what if my laptop stops in between training model. Can i continue from where i left? I dont want to waste time to start training again from the start. Since i have trained for 30+ hours. Right now i m near 2.5 Epochs.
