### ISSUE TITLE
Vjoy for MacOS?

### ISSUE THREAD

**Issue by FeatheryW** [Sentdex/pygta5#134]
Want to know if it's possible to get Vjoy working on MacOS. I know you aren't working on this project much at the moment but if anyone knows or can help, I'm just trying to figure out how to simulate pushing buttons on a joystick on a mac.

Thanks in advance!

**Comment by UlucFVardar** [comment]
> Want to know if it's possible to get Vjoy working on MacOS. I know you aren't working on this project much at the moment but if anyone knows or can help, I'm just trying to figure out how to simulate pushing buttons on a joystick on a mac.
> 
> Thanks in advance!

Hello, Same question. Did you solve it?
