### ISSUE TITLE
Im trying to test the model

### ISSUE THREAD

**Issue by DualByte** [Sentdex/pygta5#137]
`Traceback (most recent call last):
  File "3. test_model.py", line 231, in <module>
    main()
  File "3. test_model.py", line 135, in main
    delta_count_last = motion_detection(t_minus, t_now, t_plus)
  File "C:\Users\d0b\GTAV PYTHON AI\Versions\v0.03\motion.py", line 46, in motion_detection
    dst = cv2.addWeighted(screen,1.0, delta_view,0.6,0)
NameError: name 'screen' is not defined`

**Comment by FurkanThePythoneer** [comment]
> `Traceback (most recent call last): File "3. test_model.py", line 231, in <module> main() File "3. test_model.py", line 135, in main delta_count_last = motion_detection(t_minus, t_now, t_plus) File "C:\Users\d0b\GTAV PYTHON AI\Versions\v0.03\motion.py", line 46, in motion_detection dst = cv2.addWeighted(screen,1.0, delta_view,0.6,0) NameError: name 'screen' is not defined`
Did you solve the problem.
