### ISSUE TITLE
Car Only Goes Straight No Matter what

### ISSUE THREAD

**Issue by udaymistry** [Sentdex/pygta5#138]
I have been training my data from past week or so I've trained around 100k samples still it just keep choosing straight no matter what any ideas how to at least make him turn according to road or something I understand that it is completely on my dataset still I just want to make a decent model that follows road if anyone can share their trained model I can see. I am using the inception model_v3 is it correct one or not I don't know but any help would be appreciated

**Comment by SherlocKOficial** [comment]
Same issue here.

**Comment by SherlocKOficial** [comment]
https://youtu.be/MGwEOxY2ygU?t=570

**Comment by udaymistry** [comment]
So Your Model Works Fine Now ? Any possibilities that you can share your model if you do not mind

**Comment by Mombuca22** [comment]
Well, I am facing the same issue. Anyone know how I run xception.py or weighting_class_distributor.py ?
Cause get_model function is not called for nothing.

Thanks.

**Comment by FurkanThePythoneer** [comment]
@SherlocKOficial , @udaymistry Because in your training data you are nearly going always straight. So that causes a problem. You need to balance the data. You can find the cod ein older versions just requires a modification.
