### ISSUE TITLE
Expected shape of ndim=4, got ndim=3, test_model.py

### ISSUE THREAD

**Issue by codelearnern** [Sentdex/pygta5#148]
Hi, I tried using v0.03 of this.  Since this project is technically using tf 1, I build an xception model in keras that works with tf 2, it is basically just an advanced CNN.  The train_model.py code is at https://mystb.in/wobemagohi.py.  My xception model code is at https://mystb.in/ezorodifek.py.  The training works perfectly fine, it's just my test_model that is having issues.  The error is `ValueError: Input 0 of layer sequential is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: [32, 270, 3]`  The test_model code is at https://mystb.in/levodosubu.py.  Thanks!

**Comment by codelearnern** [comment]
Solved with a np.reshape

**Comment by FurkanThePythoneer** [comment]
> Solved with a np.reshape

Hi, can you share your Xception model? I am having hard time to run sentdex's model.

**Comment by codelearnern** [comment]
> > Solved with a np.reshape
> 
> Hi, can you share your Xception model? I am having hard time to run sentdex's model.

Yeah sure, https://github.com/codelearnern/tweakedSelfDrive
