### ISSUE TITLE
"Failed to interpret file %s as a pickle" % repr(file))

### ISSUE THREAD

**Issue by RaitKivinurm** [Sentdex/pygta5#154]
Hi

I am getting an error sometimes and I do not know how to fix it :(
I am at the 10. video and the code I am having is like this:
`file_name = 'training_data.npy'`

`if os.path.isfile(file_name):`
`    print('Loading Data..')`
`    training_data = list(np.load(file_name))`
`else:`
`    print('No data file, starting fresh')`
`    training_data = []`

and error:
`C:\Users\rait.grp\PycharmProjects\pyGTA\venv\Scripts\python.exe C:/Users/rait.grp/PycharmProjects/pyGTA/main.py`
`Traceback (most recent call last):`
`  File "C:\Users\rait.grp\PycharmProjects\pyGTA\venv\lib\site-packages\numpy\lib\npyio.py", line 447, in load`
`    return pickle.load(fid, **pickle_kwargs)`
`EOFError: Ran out of input`
``
`During handling of the above exception, another exception occurred:`
``
`Traceback (most recent call last):`
`  File "C:/Users/rait.grp/PycharmProjects/pyGTA/main.py", line 163, in <module>`
`    training_data = list(np.load(file_name))`
`  File "C:\Users\rait.grp\PycharmProjects\pyGTA\venv\lib\site-packages\numpy\lib\npyio.py", line 450, in load`
`    "Failed to interpret file %s as a pickle" % repr(file))`
`OSError: Failed to interpret file 'training_data.npy' as a pickle`
`Loading Data..`

`Process finished with exit code 1`

**Comment by RaitKivinurm** [comment]
i noticed that every time I have this error my training data has been erased by the previous training session.

now I know that I have to keep backups until i find the reason

**Comment by IQraQasim10** [comment]
I am watching this thread after about a year, and I encountered the same issue today. Any solutions?

**Comment by daniel-kukiela** [comment]
In the middle of the error message above it says:
```
EOFError: Ran out of input
```
This means the file has not been saved fully. The most possible reason would be the script has been terminated in the middle of data saving. To prevent this either make sure to terminate the script when the file is saved or add a way to exit it cleanly (for example, in the code, add a check if some defined key is pressed and invoke exit() - this way the script will always exit only here and not while the file is being saved)
