### ISSUE TITLE
Can someone share the trained data? Thank you

### ISSUE THREAD

**Issue by GatherStar** [Sentdex/pygta5#157]
I am a novice, I can train the data with exhaustion, but it keeps going straight. I don't know if I did it right.

**Comment by birdy0017** [comment]
It looks like I have found it,
https://pythonprogramming.net/more-interesting-self-driving-python-plays-gta-v/

**Comment by FurkanThePythoneer** [comment]
@birdy0017 Only AlexNet trained model is shared. However the reason your car goes straight is you probably didn't balanced the data. If you want I can share my _**modified balance**_ data with you.
