### ISSUE TITLE
There is no such a thing as BalanceData.py ?

### ISSUE THREAD

**Issue by FurkanThePythoneer** [Sentdex/pygta5#159]
I gave my hours to develop a good model but there was a problem. My Agent was always going straight. I have tried anything for hours but then i realized "Nearly all of my data is going straight" i need to balance data! I think missing file is one of the huge issues. I know it's been 3 years but there are still people coming this repo giving their hours and have nothing! So create a python file called Balance Data so we can tbalance our data.

**Comment by lilmnm-kamikaze-** [comment]
if you look in [Tutorial Codes/Part 14-15/balance_data.py](https://github.com/Sentdex/pygta5/blob/master/Tutorial%20Codes/Part%2014-15/balance_data.py). It has one there. i used it before and it worked when i had the only going straight issue.

**Comment by FurkanThePythoneer** [comment]
@lilmnm-kamikaze- yeah but in that file it's just balancing it to: W A D . In the last version there is all combination of moving. So i think it must be modified.
