### ISSUE TITLE
Can someone upload the trained model for Googlenet?

### ISSUE THREAD

**Issue by naga-k** [Sentdex/pygta5#162]
I would like to run a trained model for googlenet but I cant find it anywhere

**Comment by FurkanThePythoneer** [comment]
@naga-k WDYM by 'run a trained model' if you are looking for **the** trained Googlenet model it's not released. (and probably won't be released :d)Only alexnet_V2 models are released by the authors. You gotta train yourself.

**Comment by Guanshuyan** [comment]
@FurkanThePythoneer Hi,i wander where  is alexnet_V2 models you mentioned?

**Comment by lilmnm-kamikaze-** [comment]
I believe they were in the written tutorial as links

**Comment by PrAsAnNaRePo** [comment]
it's inception-v3
