### ISSUE TITLE
It seems to have some problem with shuffle function in balance.py

### ISSUE THREAD

**Issue by fevemania** [Sentdex/pygta5#18]
There is the simple 2000 data (no shuffle) with 1682 forwards, 161 lefts, 157 rights

But after using shuffle in build-in random library, It comes out with unpredictable result. (and I already test for more than 5 times, every time with different result.)

![_2017_04_28_17_47_20_127](https://cloud.githubusercontent.com/assets/16337667/25523921/0beb5658-2c3b-11e7-9afb-aca3a14df7d0.png)

so I try to use shuffle method in numpy library. And the result is always correct.

![_2017_04_28_17_48_32_618](https://cloud.githubusercontent.com/assets/16337667/25523928/12390668-2c3b-11e7-8396-ba96666002a0.png)

@Sentdex  Would you mind for testing it, Thx.

**Comment by Sentdex** [comment]
Yeah, I came across this, I honestly have no idea what is happening there, makes no sense to me why that'd be happening. The way I "solved" it was to put the data into a pandas dataframe, and shuffle that. Doing that gives the results one would expect.

A few models were trained by me on the old method and it still appears to work, and I looked into the data itself and it appeared correct, but the behavior of the counts still baffles me. 


Here's the code I have been using to do the shuffling:

```
        train_data = np.load('training_data-{}.npy'.format(i))
        df = pd.DataFrame(train_data)
        df = df.iloc[np.random.permutation(len(df))]
```

I will soon be updating the repo as well with these changes.
