### ISSUE TITLE
Implement xInput for fine control

### ISSUE THREAD

**Issue by bayangan1991** [Sentdex/pygta5#25]
Hey @Sentdex,
Creating an issue just for visibility as I no longer think a pull request is necessary. I don't know enough about machine learning (yet!) to properly work it in to your code.

Head over to https://github.com/bayangan1991/PYXInput for my python package for creating a virtual xbox controller. Fully documented and a legit PyPI package.

I have tested this with Rocket League, the only car game I own, and it works perfectly.

I am super excited to see what you can do with my code!

**Comment by Sentdex** [comment]
Hmm, I will leave this open for now. I actually wound up implementing vjoy + x360xce myself, but I will still try to look into this, it looks like this is more of a packaged up version that other people could use more easily than my implementation + steps for downloading the rest of the requirements :P

**Comment by bayangan1991** [comment]
It's run in to a few issues with the latest Win 10 updates but it works well with a little debugging.

I've been burned by not documenting too many times before! Easier to just make it a habit.
