### ISSUE TITLE
Charles walking around downtown LS

### ISSUE THREAD

**Issue by linco95** [Sentdex/pygta5#31]
I went into the stream today (051417) and saw Charles walking around. I did not see how he got out of his car, and it might have been intentional, but just in case I thought I'd let you know.

https://clips.twitch.tv/EsteemedInspiringTeaKreygasm

edit: spawning without car https://clips.twitch.tv/NastyScaryPepperRickroll

**Comment by Ghost---Shadow** [comment]
I tried running the net outside the car. It behaved similarly as shown in the video.

**Comment by Sentdex** [comment]
Sometimes, despite locking doors, he gets grabbed out of the vehicle.
