### ISSUE TITLE
Headless execution of the code

### ISSUE THREAD

**Issue by rach0012** [Sentdex/pygta5#32]
Is it possible to get the code to work when we have no GUI (for example running the code on a server)? The current code wants the window in the corner or visible in order to capture screenshots - any workaround the same? 

Thanks!

**Comment by H3npi** [comment]
since you need the game to let charles see something, i see no reason in running the code on a server. Somehow Charles needs to see something

**Comment by Sentdex** [comment]
ATM, I see no way of running this headless, as the crux of this is using the screenshots from the background. I am sure there's a way to instead run GTA V headless and to grab what should be the visual output, but that's not something I am capable of writing. 

Would LOVE to see such a thing though!

**Comment by rach0012** [comment]
Managed to solve this - used selenium headless browser to do so - works great thus far!
