### ISSUE TITLE
Training data incorrect 

### ISSUE THREAD

**Issue by Dahandla** [Sentdex/pygta5#43]
Hello Sentdex,
First I 'd like to thank you for your wonderful tutorials 
I have been following along with your tutorials and I am on part 9-10 of “Python plays GTA”
So I ran into an issue with the “create training data script”, after recording training data when I go to balance I notice that I only have 

                                                   0          1
0  [[3, 3, 6, 7, 7, 6, 6, 11, 6, 5, 6, 6, 4, 3, 3...  [0, 1, 0]
1  [[3, 4, 6, 8, 8, 7, 7, 14, 9, 7, 6, 7, 5, 4, 4...  [0, 1, 0]
2  [[4, 4, 6, 8, 8, 8, 8, 17, 11, 7, 7, 7, 5, 4, ...  [0, 1, 0]
3  [[4, 5, 7, 9, 9, 8, 9, 20, 14, 8, 7, 8, 6, 5, ...  [0, 1, 0]
4  [[5, 5, 8, 10, 10, 10, 9, 27, 19, 9, 8, 9, 7, ...  [0, 1, 0]
Counter({'[0, 1, 0]': 3000})

looks like only one output from keys

and that's going forward only no left or right
I have pywin32 installed, any idea what could be wrong?

1. Just started learning python so I fairly new to all of this, but I have a grasp on what's going on with the scripts so far .. is there another way of getting key input into the code?

Any help would be appreciated, I really looking forward to the rest of the series but I'm stuck here.

**Comment by Sentdex** [comment]
Strange, I haven't seen anyone else with this issue. Looking at: https://github.com/Sentdex/pygta5/blob/master/create_training_data.py

I really don't see how that would be caused.

**Comment by Sentdex** [comment]
Closing this for now, if you see an actual error in the code, let me know with another issue, I just don't see what in the code would cause that.

**Comment by My-captain** [comment]
Hi, Sentdex.
I've just got the reason.  The function 'win32api.GetAsyncKeyState()' in 'getkeys.py' can only detect the input in the window which the python script is running.
For example, i run the python script by IDLE,the function can only detect my input when i input in the IDLE.

Do you konw how i can solve it?I'm stuck here.

Looking forward to your reply.
