### ISSUE TITLE
Tensorboard issue

### ISSUE THREAD

**Issue by frossaren** [Sentdex/pygta5#47]
WARNING:tensorflow:Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
WARNING:tensorflow:Found more than one metagraph event per run. Overwriting the metagraph with the newest event.

Got these warnings while running tensorboard, and i cant figure out whats wrong.
after the warnings nothing happends at all

**Comment by Sentdex** [comment]
Are you possibly overwriting an existing log file (same model name as a pre-existing log had?)

**Comment by frossaren** [comment]
i am not sure. What i have done is to run train_model.py with new trainingdata every time. Am i doing wrong when i delete the old training data before training again from another sample and it therefore overwrites that log.

Also, am i supposed to rename something in the code between trainings?

**Comment by frossaren** [comment]
bumping this as i am still unsure what i am doing wrong
