### ISSUE TITLE
cuDNN status not initialized

### ISSUE THREAD

**Issue by FlameTech-Entertainment** [Sentdex/pygta5#48]
Dear sentdex,

can You help me please? I despair...
When I want to run the test_model.py, always python would not respond when this in the console happend:

E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:359] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED

cuDNN is installed and the %PATH%-variable holds the path to the cuDNN folder...
Can You send me Your %PATH%-variable as example? Maybe there is my problem....

I hope You can help me!

(Sorry for my bad english knowledgement)

**Comment by Sentdex** [comment]
https://i.gyazo.com/bee741277d721a2924e541eb45891ca2.png
