### ISSUE TITLE
Input beyond video stream

### ISSUE THREAD

**Issue by PatrikFe** [Sentdex/pygta5#49]
Hey friends,

As far as I understood in the YouTube videos and judging from what I read in the comments, it is also desirable for you to give the neural network input beyond the video stream. E.g. you would like to know the position and speed and maybe the planned trajectory of other vehicles around you.
I found this project on GitHub and I was wondering if we could integrate this: https://github.com/lgrahl/scripthookvpy3k 
To get the information beyond the video stream. It shall give us access to a rich API that is "documented" (rather enumerated) here: http://www.dev-c.com/nativedb/

What do you think?

Regards
Patrik

**Comment by Sentdex** [comment]
Hi Patrik, 

We've already been using scripthook for failsafes, along with preparing for reinforcement learning. I don't want the model itself to take inputs other than visual, but we can use GPS and some other stuff to validate what the AI does. I'd still rather not even do that, or have failsafes. Maybe one day!

**Comment by PatrikFe** [comment]
Thanks for the info. 
Can you please guide me to the video where you included scripthook for failsafes - thanks a lot.
