### ISSUE TITLE
Access Denied Tensorflow Error?

### ISSUE THREAD

**Issue by Testdude3234** [Sentdex/pygta5#50]
`Could not open C:\Users\User1\Desktop\aidrivers: Unknown: NewRandomAccessFile failed to Create/Open: C:\Users\User1\Desktop\aidrivers : Access is denied.
; Input/output error`

Why is this happening? All i did was update to the newest pygta5? I tried putting it into another folder but that doesn't seem to fix that error.

**Comment by Hehe-Zhc** [comment]
set
`MODEL_NAME = 'anything'`

`LOAD_MODEL = False`

**Comment by Testdude3234** [comment]
Okay that fixed it kinda but now there's a new error. It can't actually find any npy files when they are there.

`[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-1778.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-1276.npy'
I tried changing up the directory it was listing to my pc but it still can't find any training files.`

**Comment by mantoone** [comment]
Where did you save the files? It works fine for me, but I did need to change the paths in the scripts.

**Comment by Testdude3234** [comment]
I made a new folder and saved it to my desktop 
C:\Users\User1\Desktop\drivers

**Comment by mantoone** [comment]
If you want to save the recorded data there change the line https://github.com/Sentdex/pygta5/blob/master/1.%20collect_data.py#L101
file_name = 'X:/pygta5/phase7-larger-color/training_data-{}.npy'.format(starting_value)
to
file_name = 'C:/Users/User1/Desktop/drivers/training_data-{}.npy'.format(starting_value)

**Comment by Testdude3234** [comment]
Okay but it's also doing the same errors to the other files, like training data and testing data. but im sure testing data is just acting like that cause well training data file isn't working, i'll try your step

**Comment by Testdude3234** [comment]
Alright this isn't working Training data is just refusing to work, There must be something wrong with the current code.
`[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-417.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-1145.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-1230.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-265.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-142.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-692.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-436.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-289.npy'
[Errno 2] No such file or directory: 'J:/phase10-random-padded/training_data-1814.npy'`

**Comment by mantoone** [comment]
Did you check that the folder contains those files? I needed to adjust the FILE_I_END variable. Take a look at https://github.com/Sentdex/pygta5/blob/master/Versions/v0.03/2.%20train_model.py#L11

If you have data until training_data-100.npy, change it to FILE_I_END = 100

**Comment by Testdude3234** [comment]
The folder has training data 1 and 2 , that's it

**Comment by mantoone** [comment]
Try FILE_I_END = 2

**Comment by Testdude3234** [comment]
`Traceback (most recent call last):
  File "C:\Users\User1\Desktop\drivers\test_model.py", line 245, in <module>
    main()
  File "C:\Users\User1\Desktop\drivers\test_model.py", line 148, in main
    delta_count_last = motion_detection(t_minus, t_now, t_plus)
  File "C:\Users\User1\Desktop\drivers\motion.py", line 46, in motion_detection
    dst = cv2.addWeighted(screen,1.0, delta_view,0.6,0)
NameError: name 'screen' is not defined
`
Test_model is erroring out now. I have everything installed and just verified, Python has all the requirements satisfied

**Comment by mantoone** [comment]
Great!

There's a bug with the motion script. You need to add screen as a parameter to the function:
So change:
def motion_detection(t_minus, t_now, t_plus):
To:
def motion_detection(t_minus, t_now, t_plus, screen):

And in the test_model script add screen to the function call:
https://github.com/Sentdex/pygta5/blob/master/3.%20test_model.py#L148

**Comment by Testdude3234** [comment]
Okay now it's giving this error
``Traceback (most recent call last):
  File "test_model.py", line 245, in <module>
    main()
  File "test_model.py", line 148, in main
    delta_count_last = motion_detection(t_minus, t_now, t_plus)
TypeError: motion_detection() missing 1 required positional argument: 'screen'

**Comment by mantoone** [comment]
I suppose delta_count should be delta_count_last at
https://github.com/Sentdex/pygta5/blob/master/3.%20test_model.py#L190

**Comment by Testdude3234** [comment]
Okay well that somehow worked but it's still not training. I waited 1 hour for it to train and it "trained" yet the file never updated. and just started to repeat.

**Comment by mantoone** [comment]
What was the output from the "2. train_model.py" script? Did you add the same MODEL_NAME to the test_model script?

**Comment by Testdude3234** [comment]
I added the same model name, There's no error other then MODEL SAVED. then it just repeats the same training data over and over

**Comment by mantoone** [comment]
The model is saved every 10th epoch. It should finish automatically when it's done. By default after 30 epochs (30 passes over the data).

**Comment by DanMossa** [comment]
Hey @mantoone . I'm also having the same error. I changed 

```
MODEL_NAME = 'anything'

LOAD_MODEL = False
```

And I only have up to 
training_data-200.npy

So I set `FILE_I_END = 200`

And now I get

```
training/training_data-37.npy
training_data-37.npy 500
---------------------------------
Run id: anything
Log directory: log/
---------------------------------
Training samples: 450
Validation samples: 50
--
Cannot feed value of shape (64, 17) for Tensor 'targets/Y:0', which has shape '(?, 9)'
training/training_data-69.npy
training_data-69.npy 500
---------------------------------
Run id: anything
Log directory: log/
---------------------------------
Training samples: 450
Validation samples: 50
--
Cannot feed value of shape (64, 17) for Tensor 'targets/Y:0', which has shape '(?, 9)'
training/training_data-190.npy
training_data-190.npy 500
---------------------------------
Run id: anything
Log directory: log/
---------------------------------
Training samples: 450
Validation samples: 50
--
Cannot feed value of shape (64, 17) for Tensor 'targets/Y:0', which has shape '(?, 9)'
training/training_data-112.npy
training_data-112.npy 500
---------------------------------
Run id: anything
Log directory: log/
---------------------------------
Training samples: 450
Validation samples: 50
--
Cannot feed value of shape (64, 17) for Tensor 'targets/Y:0', which has shape '(?, 9)'
training/training_data-157.npy
training_data-157.npy 500
---------------------------------
Run id: anything
Log directory: log/
---------------------------------
Training samples: 450
Validation samples: 50
--
Cannot feed value of shape (64, 17) for Tensor 'targets/Y:0', which has shape '(?, 9)'
training/training_data-58.npy
training_data-58.npy 500
---------------------------------
Run id: anything
Log directory: log/
---------------------------------
Training samples: 450
Validation samples: 50
--
Cannot feed value of shape (64, 17) for Tensor 'targets/Y:0', which has shape '(?, 9)'
training/training_data-104.npy
training_data-104.npy 500
```

Over and over until I stop it

**Comment by DanMossa** [comment]
@mantooneoops I did change it.

Thanks mate

**Comment by mantoone** [comment]
You're welcome!

On Jul 6, 2017 12:00 AM, "Daniel Mossaband" <notifications@github.com>
wrote:

@mantooneoops I did change it.

Thanks mate

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sentdex/pygta5/issues/50#issuecomment-313225419>, or mute
the thread

**Comment by frossaren** [comment]
@mantoone It would be nice if you did a pull request on your fix for screen not defined in motion. I think many people have the same problem

**Comment by mantoone** [comment]
@frossaren There it is now: https://github.com/Sentdex/pygta5/pull/64

**Comment by frossaren** [comment]
Great!

Den 12 aug. 2017 18:18 skrev mantoone <notifications@github.com>:

@frossaren<https://github.com/frossaren> There it is now: #64<https://github.com/Sentdex/pygta5/pull/64>
