### ISSUE TITLE
Add data augmentation

### ISSUE THREAD

**Issue by mantoone** [Sentdex/pygta5#51]
Data augmentation could be used to increase the use of existing training data. For example adding images with different brightness could help making the model invariant to time of the day. 

Here's an example of what could be done:
https://chatbotslife.com/using-augmentation-to-mimic-human-driving-496b569760a9

I believe flipping or offset cannot be used in this case as the training data has key presses instead of steering angle.

**Comment by edilgin** [comment]
I also am wondering why he didn't do it, makes a lot of sense to me. And correct me if i am wrong but i think flipping can be achieved too: for example if you flip images where you are turning right to turning left and also change the key press from right to left you get the correct data. You can do this for every turning data and i think get away with it.
