### ISSUE TITLE
No balance_Data.py?

### ISSUE THREAD

**Issue by DanMossa** [Sentdex/pygta5#53]
> Currently, to use the latest version of this AI, you will need to run first "create_training_data.py," then balance this data with "balance_Data.py."

From what I understand, the finished product is what's in the root of the git folder.

I don't see a balance_Data.py file.

Am I supposed to use the one in the Part14-15 folder or is it already included in the `train_model.py` folder?

**Comment by frossaren** [comment]
No need to balance the data after the last update

**Comment by giordand** [comment]
Why it is not neccesary any more?

**Comment by DevJhns** [comment]
@giordand Did you found out, why no ballance data needed, for me only ballanced data works, i use alexnet2

**Comment by Godismannen** [comment]
if you are using 0.03V than you can use "weighting_class_distributor.py" script to make the weight match you validation data, there bu no need for balancing before,

https://youtu.be/MGwEOxY2ygU his video of charles 2.0 explain
