### ISSUE TITLE
Not returning `delta_count`

### ISSUE THREAD

**Issue by DanMossa** [Sentdex/pygta5#54]
Inside the test_model.py file, there is a line

` motion_log.append(delta_count)`

delta_count was not initialized before

and I have another line that's 

`delta_count_last = motion_detection(t_minus, t_now, t_plus)`

I'm assuming this is meant to be 

`delta_count= motion_detection(t_minus, t_now, t_plus)`
?

But then under motion.py

the function `motion_detection` has a line that says

`dst = cv2.addWeighted(screen,1.0, delta_view,0.6,0)`

But no where is screen defined.

**Comment by frossaren** [comment]
Got the same problem

**Comment by frossaren** [comment]
Found a fix for it in another issue. Said to the guy that he should make a pull request but if he doesnt do it i will make it for him. Will link the isssue for you!

**Comment by frossaren** [comment]
https://github.com/Sentdex/pygta5/issues/50 scroll a bit further down and you will find it :)

**Comment by DanMossa** [comment]
@frossaren Yeah! Honestly, this code is all fucked up lol. I ended up fixing everything up myself a few days ago :P

**Comment by frossaren** [comment]
Yeah. Unfortunatly not many People Who makes pull requests either so we are not really going anywhere

Den 12 aug. 2017 04:29 skrev Daniel Mossaband <notifications@github.com>:

@frossaren<https://github.com/frossaren> Yeah! Honestly, this code is all fucked up lol. I ended up fixing everything up myself a few days ago :P
