### ISSUE TITLE
Memory exhausted error

### ISSUE THREAD

**Issue by frossaren** [Sentdex/pygta5#59]
Hello!

While trying to train the data in the latest update i got alot of memory exhausted errors. It didnt even create a model. Is it a problem with the trainingdata that i am giving to it or isnt 4gb x2 not enought anymore? If so is there an easy way to supply it in portions so that i dont fill up the vrm or do i need to go for the slower cpu?
Currently running 2x 980 in sli
Thanks in advance //Frossaren

**Comment by johndpope** [comment]
see 20 mins in for a config you can set to avoid tensorflow hogging ram.
https://blog.altoros.com/video-and-slides-from-the-tensorflow-london-meetup-march-31-2016.html

@Sentdex - I think this is related to your memory hogging problem on your 7/8/9 video.

**Comment by johndpope** [comment]
I think you want to call tf.reset_default_graph() somewhere. although it's not clear where.
you will likely need to 
import tensorflow as tf
the code should expose this.

**Comment by frossaren** [comment]
@johndpope Where am i supposed to use this config? Tried but keeps getting the same error

**Comment by johndpope** [comment]
sorry @frossaren  - it's a stab in the dark. 
watching the tutorials - I understood that the machine learning was using tensorflow.
but searching through code - it doesn't appear - although there is a reference to tflearn.
if you can get the tensorflow session - then you should be able to configure the gpu memory options.

**Comment by frossaren** [comment]
Well then i am completely stuck. Will keep on googleing and see if i can find something useful and update here if i do.

**Comment by frossaren** [comment]
Solved by adding batch_size in the model.fit row

**Comment by johndpope** [comment]
you should do a PR. when you help another you automatically help yourself. it's like multi tasking.

**Comment by frossaren** [comment]
I will, but i will see if it affected the performance first and If it gets better with a higher batch size. Thanks for the reminder

Den 1 aug. 2017 03:14 skrev John Pope <notifications@github.com>:

you should do a PR. when you help another you automatically help yourself. it's like multi tasking.

**Comment by frossaren** [comment]
performance seemes to be unaffected so i will do a pr
