### ISSUE TITLE
Screen not defined in motion

### ISSUE THREAD

**Issue by frossaren** [Sentdex/pygta5#61]
Screen is not defined in motion.py and therefor i cant run test_model.py Anyone know what is supposed to be the screen there?

**Comment by frossaren** [comment]
found a fix in another issue. Hopefully he will make a pr or i will do it for him.

**Comment by LEOCUIZHIHAO** [comment]
Hi frossaren,

I am facing the same issue. Could you plz tell me how u fixed that?

Cheers
Leo
