### ISSUE TITLE
Reshape on train_data is mixing the pixels!

### ISSUE THREAD

**Issue by giordand** [Sentdex/pygta5#63]
The reshape to the train data and also to the screen grabbed on testing model is mixing the pixels in the screen:

![image](https://user-images.githubusercontent.com/8845274/29105682-f1aa0f44-7ca5-11e7-9ceb-6373b0132814.png)

the solution is to change width by height in every line where is a reshape, as in 
https://github.com/Sentdex/pygta5/blob/d9375c128de9f66bef60f60f4054e209b5abb35f/2.%20train_model.py#L88
`            X = np.array([i[0] for i in train]).reshape(-1,WIDTH,HEIGHT,3)`

by:

`            X = np.array([i[0] for i in train]).reshape(-1,HEIGHT,WIDTH,3)`

and now reshape is OK:

![image](https://user-images.githubusercontent.com/8845274/29105760-84c95866-7ca6-11e7-895e-6cd0e83fcbe9.png)

**Comment by germanmarky** [comment]
Confirmed issue and fix.

**Comment by Eric-Ryan** [comment]
prev = cv2.resize(screen, (WIDTH,HEIGHT))

    screen = cv2.resize(screen, (WIDTH,HEIGHT))

    prediction = model.predict([screen.reshape(WIDTH,HEIGHT,3)])[0]

Within '3.test_model.py' should I change these lines too? Did this fix the issue of only going straight?

**Comment by giordand** [comment]
This fix is no related with #62 ...at least with 25k examples for training, balanced....

**Comment by germanmarky** [comment]
@giordand I haven't had a chance to test, but good to know.

@Eric-Ryan do not change the resize functions as they are working as intended.

**Comment by DevJhns** [comment]
@giordand how you get reshaped img?
