### ISSUE TITLE
memoryerror with numpy

### ISSUE THREAD

**Issue by marius851000** [Sentdex/pygta5#65]
I've an error on wille using this on windows 10 with any x64 processor ( but an x32 python version ).
Here the error.

C:\Users\marius\Desktop\pygta5-master>python "1. collect_data.py"
File exists, moving along 1
File does not exist, starting fresh! 2
4
3
2
1
STARTING!!!
100
200
300
400
500
Traceback (most recent call last):
  File "1. collect_data.py", line 116, in <module>
    main(file_name, starting_value)
  File "1. collect_data.py", line 97, in main
    np.save(file_name,training_data)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\numpy\lib\npyio.py", line 509, in save
    pickle_kwargs=pickle_kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\numpy\lib\format.py", line 576, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
MemoryError

C:\Users\marius\Desktop\pygta5-master>

**Comment by germanmarky** [comment]
@marius851000 can you give us more info?

- How much RAM does your machine have?
- Are you resizing the image?
- Are they RGB images?
- How much free space do you have on the drive you are saving them?

I see that there is already a file saved, was that captured with no changes to 1. collect_data.py?

**Comment by marius851000** [comment]
1. I have 3,9 Go of ram
2. I have used the script without modification
3. I have approximatively 300 Go of free space
4. Yes, I've alrealy lauched the script once, It write a file of 60o, but it have also say an error

5. I've havent changed the default place of the training data

**Comment by frossaren** [comment]
You should change where the training data is supposed to be saved. That is probably the reason for the error

Den 17 aug. 2017 8:16 fm skrev marius851000 <notifications@github.com>:

  1.  I have 3,9 Go of ram

  2.  I have used the script without modification

  3.  I have approximatively 300 Go of free space

  4.  Yes, I've alrealy lauched the script once, It write a file of 60o, but it have also say an error

  5.  I've havent changed the default place of the training data

**Comment by CT83** [comment]
Having the same issue, almost the same configuration. I got my resources free, RAM 3 gigs free. Unable to record any training data. Any solutions? Did the OP find solution to his problem?

**Comment by CT83** [comment]
Btw, I am saving my training data, in the directory where the script is located, my D drive. Do I need to move it to C, for some reason?

**Comment by germanmarky** [comment]
@CT83, when running the capture script run Task Manager. If your RAM gets to about 80-90% allocated during the save process, the ndarray is to large to save. Make sure to close out all other unneeded applications that are RAM intensive which can be checked in Task Manager as well.

What you can do is change the max size of the array from 500 to 300 or even less. The actual size is arbitrary, you can increase or decrease the max size to fit the resources better in your system. 

For example, I have 32GB of RAM and can capture a 2GB output file before worrying about running out of memory.

**Comment by CT83** [comment]
Oh Thanks. Yes, @germanmarky, I was researching the problem myself later and I thought of the same thing.  Stackoverflow suggested using python64, I think I should switch to it for performance. I haven't looked over the training script yet. Do I need to make any changes to it? Btw what do you think about Hickle?

**Comment by germanmarky** [comment]
I attempted to use HDF5 for saving and loading as it's much more memory efficient but had issues matching up the containers on load and validating that the data was formatted correctly so just stayed with np.save(). 

I am also using Anaconda 4.1 64-bit and python 3.5 for my virtual env.

If you don't have the headroom in RAM to save the file, even 64-bit python won't help, but definitely won't hurt. I would start by dropping line 96 to 200 or 100 and keeping an eye on your RAM usage. You could also set it to 100 and comment out line 99 and see at what amount it actually fails, then just use that number.

**Comment by CT83** [comment]
Yes, I will try that, report here. Write a proper answer with my actual specs and what value I used. And we can close this Issue. 👍🏽

**Comment by CT83** [comment]
My PC Specifications:
Lower-Mid Spec PC
AMD A8-6600K APU with Radeon(tm) HD Graphics 3.90 GHz	
8.0 GB DDR3 1333 MHz
WD5000AZRX HDD

**Problem**: MemoryError while saving Pickle, same as OP @marius851000 
**Solution**: Changed line 96 `if len(training_data) == 500:` to `if len(training_data) == 200:`
**Result**: Pickle Saved Successfully

Issue has been resolved! @Sentdex  
Thanks to @germanmarky

**Comment by CooperShield** [comment]
Actually if anybody has another idea to solve this problem, because even by changing it to 100 doesn't help me

**Comment by birdrecluse** [comment]
I had the same problem, thinking maybe it's because of data size I tried to save all at once is too big. Therefore I made it that it saves every 2000 frames, then it worked 50% of the time, meaning it could save successfully one time and would fail another time.
And then I just made changes to my virtual memory settings, adjusting it to be 2GB instead of 1GB, and then it finally worked perfectly fine.
You can find the settings for virtual memory in Computer attribute -> Advance System Settings -> Advance tab -> Performance -> Advance tab
