### ISSUE TITLE
Step by Step installation and running code

### ISSUE THREAD

**Issue by augmen** [Sentdex/pygta5#68]
Step by Step installation and running code on Mac OS x. Please guide. I have used pip install to install NumPy. How to install Open CV ? Do i need to install opnCV in the root directory / Tensorflow visual env ?

**Comment by frossaren** [comment]
Pip install everything in requirements and if it tells you that you are missing something, try pip install that and if it doesnt work google it. It is quite straight forward so i dont think a complete step by step guide should be needed.

**Comment by augmen** [comment]
For Mac - How to install Open CV ? Do i need to install opnCV in the root directory / Tensorflow visual env ?

**Comment by augmen** [comment]
I want to know whether i need to install the opencv Xcode file ? iF I  install the normal opencv from the GitHub and whether i need to symlink the python libs from the virtual env of tensor flow with the opencv ?

**Comment by clebio** [comment]
There's a lot of things wrong with this repo. What version of Python are you using? How do you install the packages in `requirements.txt` even on Windows -- are you using Anaconda, Enthought, [Golhke's packages](http://www.lfd.uci.edu/~gohlke/pythonlibs/)?

The paths in the 1/2/3 steps are all over the place, and hard-coded. Why aren't you using `os.path.join`, etc.?
https://github.com/Sentdex/pygta5/blob/master/1.%20collect_data.py#L101
https://github.com/Sentdex/pygta5/blob/master/2.%20train_model.py#L63

I'd love to help, but not sure I can even get things running.

ps: this issue should be title "on mac OS", or something.

**Comment by mdraju4201** [comment]
hi! everyone. i"m new here Please someone guide me how to do it from the beginning.
