### ISSUE TITLE
Download Pre-trained newer version models

### ISSUE THREAD

**Issue by viv696** [Sentdex/pygta5#87]
How to download Pre-trained newer version(v0.02 onwards) models, trained on 1 million datasets?

**Comment by TahaMostafa** [comment]
i hope you reach it and send it to me

**Comment by GokulEpiphany** [comment]
any place where we can dl the earliest model? or shuld we gather training data and train it ourselves?

**Comment by Data-Scientist-Singh** [comment]
is it ok to collect the data for this project and post it in here ?

**Comment by shreyas-7** [comment]
> Does

 anyone have links to any of the trained models?
Please do share.

**Comment by udaymistry** [comment]
Can Someone Please Share Their Trained Models I Have a Cpu And I can not train it for a month but I want to see how it works after models if anyone is kind enough to do this favor
