### ISSUE TITLE
in motion.py "screen" in not defined!

### ISSUE THREAD

**Issue by hemanth2410** [Sentdex/pygta5#88]
![screenshot 125](https://user-images.githubusercontent.com/24288422/35447643-3ee1fff6-02de-11e8-8380-9d183a398d0b.png)

**Comment by hemanth2410** [comment]
it says screen is not defined

**Comment by hemanth2410** [comment]
solved issue NVM

**Comment by LEOCUIZHIHAO** [comment]
Hi hemanth,

I am facing the same issue. Could you plz tell me how u fixed that?

Cheers
Leo
