### ISSUE TITLE
Improving FPS capture rate

### ISSUE THREAD

**Issue by tzickel** [Sentdex/pygta5#9]
Check out my gist where I've ported some C code from another project to capture an window handle:
A. No dependencies needed besides regular python (no need for PIL or PyWin32).
B. Can capture specific window handles instead of all the desktop.
C. Very fast, about 16ms capture (even for full screen) compared to 47ms capture using ImageGrab with 800x600 bounding box.
D. Can reuse an previous allocated numpy array for the result.

https://gist.github.com/tzickel/5c2c51ddde7a8f5d87be730046612cd0

**Comment by BanditBoi** [comment]
I think there is no need for more than 20 fps.  More than 20 the Neural net would be getting similar images there is not much to learn, if the fps is much less there is less information to learn. But great improvement though. 👍

**Comment by Sentdex** [comment]
Thanks for sharing this. Currently using neural networks more than 20fps isn't necessarily needed, but I'd rather have the best possible and arbitrarily control the FPS myself than be forced into it with slower code.

**Comment by tzickel** [comment]
You can always space the grabbing better in a second when it's faster.

Also the current code does in each call quite a few large mallocs (and copying) for the framebuffer. Twice in GetBitmapBits (once as a normal malloc to get it from win32api, second for converting it to a python string), and then another one in the code np.fromstring (np.frombuffer btw will re-use it, and not create another copy).

My code can do just one allocation at start, and then reuse it for the next grabbing.

**Comment by Flandan** [comment]
This is working great for me

**Comment by davidskuza** [comment]
If you can grab screen in 16 ms instead of 50 you have 34 ms for other calculations to get real 20 fps. If you get screen in 50 and do some preview rendering, predicting or whatever it is not 20 fps anymore.

**Comment by tzickel** [comment]
No need to argue, BTW, anybody should feel free to take that snippet and submit an PR if it works for him.

**Comment by kelvinjou** [comment]
Does it work for mac as well? I haven't tried it yet but I think I see a few "win" keywords, a shorthand for windows...?
