### ISSUE TITLE
Run AI in the background with the game in fullscreen mode?

### ISSUE THREAD

**Issue by the-machine-preacher** [Sentdex/pygta5#99]
I've managed to mod the AI to play Skyrim (Enhanced Edition), PUBG and Fortnite but these games are GPU heavy and I barely get 1FPS with them running in windowed mode with the AI in the background. Once I make the games fullscreen, the AI stops working. These games were optimized for fullscreen-mode.

How do I circumvent this and keep the AI running in the background?

**Comment by M3L0NM4N** [comment]
I'm sorry I don't know the answer to your question, but could you possibly share how you modded the AI to play those games? I'm trying to mod it to play some of those games as well, but I have had no luck.

**Comment by SnailingGoat** [comment]
I don't thing that the AI (or proper saying Neural Network) should stop working when you make it full screen.. Could you possibly send me your files? And maybe better describe your issue...

Petr Gardas a.k.a SnailingGoat
